# Generated by Django 3.0.5 on 2022-03-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_identifier', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BotUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.BooleanField(default=False)),
                ('subscriptions', models.BooleanField(default=False)),
                ('support_contact', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botUsers.BotUser')),
            ],
        ),
    ]
