# Generated by Django 3.0.5 on 2021-11-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botUsers.BotUser')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instances.Instance')),
                ('target_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instances.Steps')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
