# Generated by Django 3.0.5 on 2021-11-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='uid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
