# Generated by Django 3.0.5 on 2020-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='steps',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
