# Generated by Django 3.0.5 on 2020-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20200912_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
