# Generated by Django 3.0.5 on 2020-09-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20200927_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
