# Generated by Django 3.0.5 on 2020-10-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20200927_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
